import { StyleSheet } from "react-native";

import { colors, controlSizes, radius, spacing, typeScale } from "../../theme";

export const routeListStyles = StyleSheet.create({
  screen: {
    flex: 1,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.control,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
    marginTop: spacing.md,
    marginBottom: spacing.sm,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  title: {
    flex: 1,
    minWidth: 0,
    color: colors.ink,
    fontSize: 24,
    fontWeight: "800",
    lineHeight: 28,
  },
  signOutButton: {
    minHeight: controlSizes.compact,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.xs,
    borderRadius: radius.pill,
    backgroundColor: "transparent",
  },
  signOutButtonPressed: {
    backgroundColor: colors.appleBlueSoft,
    transform: [{ scale: 0.985 }],
  },
  signOutButtonText: {
    color: colors.muted,
    fontSize: typeScale.xs,
    fontWeight: "800",
  },
  mapReturnButton: {
    minHeight: controlSizes.compact,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.sm,
    borderWidth: 0,
    borderRadius: radius.pill,
    backgroundColor: colors.appleBlueSoft,
  },
  mapReturnButtonPressed: {
    transform: [{ scale: 0.985 }],
  },
  mapReturnButtonText: {
    color: colors.appleBlue,
    fontSize: typeScale.xs,
    fontWeight: "900",
  },
  noticeBox: {
    alignSelf: "center",
    maxWidth: "100%",
    minHeight: controlSizes.compact,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderWidth: 0.5,
    borderColor: colors.borderSoft,
    borderRadius: radius.pill,
    backgroundColor: colors.appleBlueSoft,
  },
  noticeText: {
    color: colors.appleBlue,
    fontSize: typeScale.sm,
    fontWeight: "700",
    lineHeight: 18,
    textAlign: "center",
  },
  clientTabs: {
    gap: spacing.sm,
    paddingBottom: spacing.sm,
  },
  clientTab: {
    maxWidth: 160,
    minHeight: controlSizes.compact,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    paddingHorizontal: spacing.md,
    borderWidth: 0.5,
    borderColor: colors.borderSoft,
    borderRadius: radius.pill,
    backgroundColor: colors.surfaceGlass,
  },
  clientTabActive: {
    backgroundColor: colors.appleBlue,
  },
  clientTabPressed: {
    transform: [{ scale: 0.985 }],
  },
  clientTabText: {
    maxWidth: "100%",
    flexShrink: 1,
    color: colors.ink,
    fontSize: typeScale.sm,
    fontWeight: "800",
    textAlign: "center",
  },
  clientTabTextActive: {
    color: colors.surface,
  },
  searchBox: {
    minHeight: controlSizes.secondary,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: spacing.sm,
    borderWidth: 0.5,
    borderColor: colors.borderSoft,
    borderRadius: radius.pill,
    backgroundColor: colors.surfaceGlass,
  },
  searchBoxFocused: {
    borderColor: colors.appleBlue,
    backgroundColor: colors.surfaceTranslucent,
  },
  searchInput: {
    flex: 1,
    color: colors.ink,
    fontSize: typeScale.sm,
    fontWeight: "600",
  },
  listSummaryRow: {
    minHeight: 28,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  listSummaryText: {
    flex: 1,
    color: colors.muted,
    fontSize: typeScale.xs,
    fontWeight: "700",
  },
  clearSearchButton: {
    minHeight: controlSizes.compact,
    justifyContent: "center",
    paddingHorizontal: spacing.xs,
    borderRadius: radius.pill,
    backgroundColor: "transparent",
  },
  clearSearchButtonPressed: {
    backgroundColor: colors.appleBlueSoft,
  },
  clearSearchText: {
    color: colors.appleBlue,
    fontSize: typeScale.xs,
    fontWeight: "800",
  },
  errorBox: {
    alignSelf: "center",
    maxWidth: "100%",
    minHeight: controlSizes.secondary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    marginTop: spacing.sm,
    marginBottom: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderWidth: 0.5,
    borderColor: "rgba(216, 74, 63, 0.18)",
    borderRadius: radius.xl,
    backgroundColor: colors.dangerSoft,
  },
  errorCopy: {
    flex: 1,
    flexShrink: 1,
    gap: 2,
  },
  errorTitle: {
    color: colors.dangerText,
    fontSize: typeScale.sm,
    fontWeight: "800",
  },
  errorText: {
    color: colors.dangerText,
    fontSize: typeScale.xs,
    fontWeight: "600",
    lineHeight: 16,
  },
  retryButton: {
    minHeight: controlSizes.compact,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.sm,
    borderRadius: radius.pill,
    backgroundColor: "transparent",
  },
  retryButtonPressed: {
    backgroundColor: colors.surfaceGlass,
  },
  retryText: {
    color: colors.dangerText,
    fontSize: typeScale.xs,
    fontWeight: "800",
  },
  loadingState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.md,
  },
  loadingCard: {
    alignSelf: "center",
    minHeight: controlSizes.secondary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    borderWidth: 0.5,
    borderColor: colors.borderSoft,
    borderRadius: radius.pill,
    backgroundColor: colors.surfaceGlass,
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0,
  },
  loadingTitle: {
    color: colors.ink,
    fontSize: typeScale.sm,
    fontWeight: "800",
  },
  routeList: {
    gap: spacing.sm,
    paddingTop: spacing.xs,
    paddingBottom: spacing.xl,
  },
  offlineNotice: {
    alignSelf: "center",
    marginBottom: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: radius.pill,
    backgroundColor: colors.surfaceGlass,
  },
  offlineNoticeText: {
    color: colors.inkSoft,
    fontSize: typeScale.xs,
    fontWeight: "700",
    textAlign: "center",
  },
  emptyState: {
    alignSelf: "center",
    alignItems: "center",
    maxWidth: 320,
    gap: 3,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderWidth: 0,
    borderRadius: radius.xl,
    backgroundColor: colors.surfaceGlass,
  },
  emptyTitle: {
    color: colors.ink,
    fontSize: typeScale.sm,
    fontWeight: "800",
  },
  emptyCopy: {
    color: colors.muted,
    fontSize: typeScale.xs,
    fontWeight: "500",
    textAlign: "center",
  },
});
