import { StyleSheet } from 'react-native';

import { authColors } from '../auth/authDesign';

export const workspaceSelectionStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: authColors.background,
  },
  safeArea: {
    flex: 1,
  },
  topBar: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
  },
  brand: {
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  logo: {
    width: 32,
    height: 32,
    resizeMode: 'contain',
  },
  brandName: {
    color: authColors.text,
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: 0,
  },
  signOutButton: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    paddingHorizontal: 10,
    borderRadius: 8,
  },
  signOutButtonPressed: {
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  signOutText: {
    color: '#C9D9F2',
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 34,
    paddingBottom: 24,
  },
  scrollContentCompact: {
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  content: {
    width: '100%',
    maxWidth: 430,
    alignSelf: 'center',
  },
  eyebrow: {
    color: '#7FCF9A',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0,
    textAlign: 'center',
  },
  title: {
    marginTop: 8,
    color: authColors.text,
    fontSize: 29,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 35,
    textAlign: 'center',
  },
  subtitle: {
    maxWidth: 360,
    marginTop: 10,
    alignSelf: 'center',
    color: '#A6A8AE',
    fontSize: 14.5,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 21,
    textAlign: 'center',
  },
  accountLabel: {
    marginTop: 12,
    color: '#7F8596',
    fontSize: 12.5,
    fontWeight: '500',
    letterSpacing: 0,
    textAlign: 'center',
  },
  listSection: {
    marginTop: 32,
  },
  listSectionCompact: {
    marginTop: 22,
  },
  sectionLabel: {
    marginBottom: 10,
    color: '#B9BDC8',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0,
  },
  workspaceList: {
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    borderRadius: 8,
    backgroundColor: 'rgba(12,16,25,0.58)',
  },
  workspaceRow: {
    minHeight: 76,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(255,255,255,0.12)',
  },
  workspaceRowLast: {
    borderBottomWidth: 0,
  },
  workspaceRowSelected: {
    backgroundColor: 'rgba(10,132,255,0.14)',
  },
  workspaceRowPressed: {
    backgroundColor: 'rgba(255,255,255,0.10)',
  },
  workspaceIcon: {
    width: 42,
    height: 42,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.07)',
  },
  workspaceIconSelected: {
    borderColor: 'rgba(92,176,255,0.38)',
    backgroundColor: 'rgba(92,176,255,0.14)',
  },
  workspaceCopy: {
    minWidth: 0,
    flex: 1,
  },
  workspaceName: {
    color: '#E7E9EE',
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 21,
  },
  workspaceNameSelected: {
    color: '#FFFFFF',
  },
  workspaceHint: {
    marginTop: 3,
    color: '#858A96',
    fontSize: 12.5,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 17,
  },
  selectionControl: {
    width: 24,
    height: 24,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.30)',
    borderRadius: 12,
  },
  selectionControlSelected: {
    borderColor: '#5CB0FF',
    backgroundColor: '#0A84FF',
  },
  statusRow: {
    minHeight: 22,
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  statusText: {
    minWidth: 0,
    flex: 1,
    color: '#8E93A0',
    fontSize: 12.5,
    fontWeight: '500',
    letterSpacing: 0,
    lineHeight: 18,
  },
  errorText: {
    color: '#FFB4B8',
  },
  emptyState: {
    minHeight: 190,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 28,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    borderRadius: 8,
    backgroundColor: 'rgba(12,16,25,0.58)',
  },
  emptyIcon: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 24,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  emptyTitle: {
    marginTop: 15,
    color: authColors.text,
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: 0,
    textAlign: 'center',
  },
  emptyMessage: {
    maxWidth: 300,
    marginTop: 7,
    color: '#959AA7',
    fontSize: 13.5,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 19,
    textAlign: 'center',
  },
  retryButton: {
    minHeight: 44,
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 14,
    borderRadius: 8,
    backgroundColor: 'rgba(92,176,255,0.12)',
  },
  retryButtonPressed: {
    backgroundColor: 'rgba(92,176,255,0.20)',
  },
  retryText: {
    color: '#7CC0FF',
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0,
  },
  footer: {
    width: '100%',
    maxWidth: 430,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingTop: 10,
    paddingBottom: 12,
  },
  footerCompact: {
    paddingHorizontal: 20,
  },
  continueButton: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
    paddingHorizontal: 20,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
  },
  continueButtonPressed: {
    backgroundColor: '#E9E9ED',
    transform: [{ scale: 0.985 }],
  },
  continueButtonDisabled: {
    opacity: 0.48,
  },
  continueText: {
    minWidth: 0,
    flexShrink: 1,
    color: '#12141A',
    fontSize: 16.5,
    fontWeight: '700',
    letterSpacing: 0,
    textAlign: 'center',
  },
});
