import { StyleSheet } from "react-native";

import { colors, controlSizes, radius, spacing, typeScale } from "../../theme";

export const routeSummaryStyles = StyleSheet.create({
  bottomSheet: {
    position: "absolute",
    right: 14,
    bottom: 14,
    left: 14,
    paddingHorizontal: 16,
    paddingTop: 12,
    borderWidth: 0.5,
    borderColor: colors.borderSoft,
    borderRadius: radius.sheet,
    backgroundColor: colors.surface,
    shadowColor: "#000000",
    shadowOpacity: 0.12,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  bottomSheetCompact: {
    paddingHorizontal: spacing.md,
  },
  bottomSheetCompactNavigation: {
    paddingTop: spacing.sm,
  },
  identityRow: {
    minHeight: 26,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  routeTitle: {
    flex: 1,
    minWidth: 0,
    color: colors.ink,
    fontSize: 18,
    fontWeight: "800",
    lineHeight: 22,
  },
  statusPill: {
    minWidth: 0,
    maxWidth: 116,
    minHeight: 26,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
    flexShrink: 1,
    paddingHorizontal: 9,
    borderRadius: radius.pill,
  },
  statusPillCompact: {
    maxWidth: 112,
    minHeight: 28,
  },
  statusPillLive: {
    backgroundColor: colors.appleBlueSoft,
  },
  statusPillDemo: {
    backgroundColor: colors.safeSoft,
  },
  statusPillDanger: {
    backgroundColor: colors.dangerSoft,
  },
  statusDot: {
    width: 7,
    height: 7,
    flexShrink: 0,
    borderRadius: radius.pill,
  },
  statusDotLive: {
    backgroundColor: colors.appleBlue,
  },
  statusDotDemo: {
    backgroundColor: colors.safe,
  },
  statusDotDanger: {
    backgroundColor: colors.danger,
  },
  statusText: {
    maxWidth: "100%",
    minWidth: 0,
    flexShrink: 1,
    fontSize: typeScale.xs,
    fontWeight: "800",
    textAlign: "center",
  },
  statusTextLive: {
    color: colors.appleBlue,
  },
  statusTextDemo: {
    color: colors.safeText,
  },
  statusTextDanger: {
    color: colors.dangerText,
  },
  endpointRow: {
    minHeight: 36,
    flexDirection: "row",
    alignItems: "stretch",
    gap: spacing.sm,
    marginTop: 6,
    paddingVertical: 2,
  },
  endpointRail: {
    width: 12,
    alignItems: "center",
    justifyContent: "space-between",
    flexShrink: 0,
  },
  endpointDot: {
    width: 9,
    height: 9,
    zIndex: 2,
    borderWidth: 2,
    borderColor: colors.onAccent,
    borderRadius: radius.pill,
  },
  endpointDotOrigin: {
    backgroundColor: colors.safe,
  },
  endpointDotDestination: {
    backgroundColor: colors.appleBlue,
  },
  endpointLine: {
    position: "absolute",
    top: 8,
    bottom: 8,
    width: 2,
    backgroundColor: colors.border,
  },
  endpointCopy: {
    flex: 1,
    minWidth: 0,
    justifyContent: "space-between",
    paddingVertical: 1,
  },
  endpointText: {
    color: colors.inkSoft,
    fontSize: typeScale.sm,
    fontWeight: "600",
    lineHeight: 17,
  },
  metricsRow: {
    minHeight: 46,
    flexDirection: "row",
    alignItems: "stretch",
    marginTop: 9,
    paddingVertical: 5,
    borderRadius: 14,
    backgroundColor: colors.quiet,
  },
  metric: {
    flex: 1,
    minWidth: 0,
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  metricDivider: {
    width: 0.5,
    marginVertical: 3,
    backgroundColor: colors.borderSoft,
  },
  metricLabel: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: "700",
  },
  metricValue: {
    marginTop: 2,
    color: colors.ink,
    fontSize: 15,
    fontWeight: "800",
    lineHeight: 18,
  },
  guestOverview: {
    paddingTop: 2,
  },
  guestDestination: {
    color: colors.ink,
    fontSize: 17,
    fontWeight: "800",
    lineHeight: 22,
  },
  guestMetrics: {
    minHeight: 22,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    marginTop: 2,
  },
  guestMetric: {
    maxWidth: "44%",
    color: colors.inkSoft,
    fontSize: typeScale.sm,
    fontWeight: "700",
  },
  guestMetricSeparator: {
    width: 3,
    height: 3,
    borderRadius: radius.pill,
    backgroundColor: colors.muted,
  },
  metricValueSafe: {
    color: colors.safeText,
  },
  metricValueAmber: {
    color: colors.amberText,
  },
  metricValueBlue: {
    color: colors.infoText,
  },
  compactSummaryRow: {
    minHeight: 34,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  compactSummaryCopy: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "baseline",
    gap: spacing.sm,
  },
  compactEtaText: {
    minWidth: 0,
    flexShrink: 1,
    color: colors.ink,
    fontSize: typeScale.xl,
    fontWeight: "800",
    lineHeight: 26,
  },
  remainingMetricLine: {
    minWidth: 0,
    flexShrink: 1,
    color: colors.inkSoft,
    fontSize: typeScale.xs,
    fontWeight: "800",
  },
  detailsPanel: {
    marginTop: spacing.sm,
    paddingTop: spacing.sm,
    borderTopWidth: 0.5,
    borderTopColor: colors.borderSoft,
  },
  detailsPrimary: {
    color: colors.ink,
    fontSize: typeScale.xs,
    fontWeight: "800",
  },
  detailsSecondary: {
    marginTop: 2,
    color: colors.inkSoft,
    fontSize: typeScale.xs,
    fontWeight: "700",
  },
  routeDescription: {
    marginTop: spacing.xs,
    color: colors.inkSoft,
    fontSize: typeScale.xs,
    fontWeight: "600",
    lineHeight: 16,
  },
  actionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    marginTop: 8,
  },
  actionRowCompactNavigation: {
    marginTop: spacing.xs,
  },
  actionRowGuest: {
    gap: 6,
    marginTop: spacing.sm,
  },
  startButton: {
    minHeight: controlSizes.secondary,
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 15,
    backgroundColor: colors.appleBlue,
  },
  startButtonCompactNavigation: {
    minHeight: controlSizes.secondary,
  },
  startButtonGuest: {
    borderRadius: 14,
  },
  startButtonDisabled: {
    borderWidth: 0.5,
    borderColor: colors.borderSoft,
    backgroundColor: colors.controlStrong,
  },
  startButtonPressed: {
    backgroundColor: colors.appleBluePressed,
    transform: [{ scale: 0.985 }],
  },
  startButtonText: {
    maxWidth: "100%",
    flexShrink: 1,
    color: colors.onAccent,
    fontSize: typeScale.md,
    fontWeight: "800",
    textAlign: "center",
  },
  startButtonTextDisabled: {
    color: colors.inkSoft,
  },
  detailsButton: {
    width: controlSizes.secondary,
    height: controlSizes.secondary,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    borderRadius: 13,
    backgroundColor: colors.control,
  },
  detailsButtonActive: {
    borderColor: colors.appleBlue,
    backgroundColor: colors.appleBlueSoft,
  },
  detailsButtonGuest: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.borderSoft,
    backgroundColor: "transparent",
  },
  detailsButtonPressed: {
    transform: [{ scale: 0.96 }],
  },
  detailsButtonDisabled: {
    opacity: 0.5,
  },
  detailsGlyph: {
    width: 22,
    height: 18,
    justifyContent: "space-between",
  },
  detailsGlyphLine: {
    width: 22,
    height: 2,
    borderRadius: radius.pill,
    backgroundColor: colors.appleBlue,
  },
  stopButton: {
    minHeight: controlSizes.primary,
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.md,
    borderWidth: 0.5,
    borderColor: colors.dangerSoft,
    borderRadius: 14,
    backgroundColor: colors.dangerSoft,
  },
  stopButtonCompactNavigation: {
    minHeight: controlSizes.secondary,
    paddingHorizontal: spacing.sm,
  },
  stopButtonPressed: {
    backgroundColor: colors.dangerSoft,
    transform: [{ scale: 0.985 }],
  },
  stopButtonText: {
    maxWidth: 64,
    flexShrink: 1,
    color: colors.dangerText,
    fontSize: typeScale.md,
    fontWeight: "800",
    textAlign: "center",
  },
});
