import { StyleSheet } from "react-native";

import {
  chrome,
  colors,
  controlSizes,
  radius,
  spacing,
  typeScale,
} from "../../theme";

export const routeListStyles = StyleSheet.create({
  screen: {
    flex: 1,
    paddingHorizontal: spacing.lg,
    backgroundColor: colors.control,
  },
  header: {
    gap: 3,
    marginTop: 3,
    marginBottom: 16,
  },
  headerTitleRow: {
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  title: {
    minWidth: 0,
    flex: 1,
    color: colors.ink,
    fontSize: typeScale.display,
    fontWeight: "800",
    lineHeight: 38,
  },
  subtitle: {
    minWidth: 0,
    color: colors.muted,
    fontSize: 14,
    fontWeight: "400",
    lineHeight: 18,
  },
  signOutButton: {
    minHeight: 36,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.xs,
    borderRadius: radius.pill,
    backgroundColor: "transparent",
  },
  signOutButtonPressed: {
    backgroundColor: colors.appleBlueSoft,
    transform: [{ scale: 0.985 }],
  },
  signOutButtonText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  noticeBox: {
    alignSelf: "center",
    maxWidth: "100%",
    minHeight: controlSizes.compact,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderWidth: 0.5,
    borderColor: colors.borderSoft,
    borderRadius: radius.pill,
    backgroundColor: colors.appleBlueSoft,
  },
  noticeText: {
    color: colors.appleBlue,
    fontSize: typeScale.sm,
    fontWeight: "700",
    lineHeight: 18,
    textAlign: "center",
  },
  clientFilter: {
    marginBottom: 18,
  },
  clientSelectorButton: {
    minHeight: 64,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 0.5,
    borderColor: "transparent",
    borderRadius: 16,
    backgroundColor: colors.surface,
    shadowColor: "#000000",
    shadowOpacity: 0.05,
    shadowRadius: 9,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
  },
  clientSelectorButtonOpen: {
    borderColor: colors.appleBlue,
    backgroundColor: colors.surfaceTranslucent,
  },
  clientSelectorButtonPressed: {
    transform: [{ scale: 0.985 }],
  },
  clientSelectorCopy: {
    minWidth: 0,
    flex: 1,
    alignItems: "flex-start",
    gap: 2,
  },
  clientSelectorLabel: {
    color: colors.muted,
    fontSize: typeScale.xs,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  clientSelectorValue: {
    minWidth: 0,
    flex: 1,
    color: colors.ink,
    fontSize: 16,
    fontWeight: "700",
  },
  clientSelectorAction: {
    flexShrink: 0,
    color: colors.appleBlue,
    fontSize: typeScale.md,
    fontWeight: "600",
  },
  clientMenu: {
    maxHeight: 220,
    marginTop: spacing.xs,
    overflow: "hidden",
    borderWidth: 0.5,
    borderColor: colors.borderSoft,
    borderRadius: radius.lg,
    backgroundColor: colors.surfaceTranslucent,
  },
  clientMenuContent: {
    padding: 4,
  },
  clientMenuItem: {
    minHeight: controlSizes.secondary,
    justifyContent: "center",
    paddingHorizontal: spacing.sm,
    borderRadius: radius.lg,
    backgroundColor: "transparent",
  },
  clientMenuItemActive: {
    backgroundColor: colors.appleBlueSoft,
  },
  clientMenuItemPressed: {
    backgroundColor: colors.surfaceGlass,
  },
  clientMenuItemText: {
    color: colors.ink,
    fontSize: typeScale.sm,
    fontWeight: "700",
  },
  clientMenuItemTextActive: {
    color: colors.appleBlue,
    fontWeight: "900",
  },
  searchBox: {
    minHeight: controlSizes.secondary,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: spacing.sm,
    borderWidth: 0.5,
    borderColor: colors.borderSoft,
    borderRadius: radius.pill,
    backgroundColor: colors.surfaceGlass,
  },
  searchBoxFocused: {
    borderColor: colors.appleBlue,
    backgroundColor: colors.surfaceTranslucent,
  },
  searchInput: {
    flex: 1,
    color: colors.ink,
    fontSize: typeScale.sm,
    fontWeight: "600",
  },
  listSummaryRow: {
    minHeight: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
    marginTop: 0,
    marginBottom: 4,
    paddingHorizontal: 4,
  },
  listSummaryText: {
    flex: 1,
    color: colors.muted,
    fontSize: 13,
    fontWeight: "600",
  },
  clearSearchButton: {
    minHeight: controlSizes.compact,
    justifyContent: "center",
    paddingHorizontal: spacing.xs,
    borderRadius: radius.pill,
    backgroundColor: "transparent",
  },
  clearSearchButtonPressed: {
    backgroundColor: colors.appleBlueSoft,
  },
  clearSearchText: {
    color: colors.appleBlue,
    fontSize: typeScale.xs,
    fontWeight: "800",
  },
  errorBox: {
    alignSelf: "center",
    maxWidth: "100%",
    minHeight: controlSizes.secondary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    marginTop: spacing.sm,
    marginBottom: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderWidth: 0.5,
    borderColor: "rgba(216, 74, 63, 0.18)",
    borderRadius: radius.xl,
    backgroundColor: colors.dangerSoft,
  },
  errorCopy: {
    flex: 1,
    flexShrink: 1,
    gap: 2,
  },
  errorTitle: {
    color: colors.dangerText,
    fontSize: typeScale.sm,
    fontWeight: "800",
  },
  errorText: {
    color: colors.dangerText,
    fontSize: typeScale.xs,
    fontWeight: "600",
    lineHeight: 16,
  },
  retryButton: {
    minHeight: controlSizes.compact,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.sm,
    borderRadius: radius.pill,
    backgroundColor: "transparent",
  },
  retryButtonPressed: {
    backgroundColor: colors.surfaceGlass,
  },
  retryText: {
    color: colors.dangerText,
    fontSize: typeScale.xs,
    fontWeight: "800",
  },
  loadingState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.md,
  },
  loadingCard: {
    alignSelf: "center",
    minHeight: controlSizes.secondary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    borderWidth: 0.5,
    borderColor: colors.borderSoft,
    borderRadius: radius.pill,
    backgroundColor: colors.surfaceGlass,
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0,
  },
  stateTitle: {
    color: colors.ink,
    fontSize: typeScale.sm,
    fontWeight: "800",
  },
  routeList: {
    gap: 12,
    paddingTop: 6,
    paddingBottom: chrome.screenBottomInset,
  },
  offlineNotice: {
    alignSelf: "center",
    maxWidth: "94%",
    marginBottom: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: radius.pill,
    backgroundColor: colors.surfaceGlass,
  },
  offlineNoticeText: {
    color: colors.inkSoft,
    fontSize: typeScale.xs,
    fontWeight: "700",
    textAlign: "center",
  },
  emptyState: {
    alignSelf: "center",
    alignItems: "center",
    maxWidth: 320,
    gap: 3,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderWidth: 0,
    borderRadius: radius.xl,
    backgroundColor: colors.surfaceGlass,
  },
  emptyCopy: {
    color: colors.muted,
    fontSize: typeScale.xs,
    fontWeight: "500",
    textAlign: "center",
  },
});
