import { StyleSheet } from 'react-native';

export const createAccountStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#0A0C11',
  },
  keyboardShell: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 30,
    paddingBottom: 36,
    paddingTop: 94,
  },
  scrollContentCompact: {
    justifyContent: 'flex-start',
    paddingHorizontal: 22,
    paddingBottom: 28,
    paddingTop: 88,
  },
  backButton: {
    position: 'absolute',
    left: 16,
    top: 24,
    zIndex: 3,
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 0.5,
    borderColor: 'rgba(255,255,255,0.16)',
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.10)',
  },
  backButtonPressed: {
    backgroundColor: 'rgba(255,255,255,0.17)',
    transform: [{ scale: 0.96 }],
  },
  backButtonDisabled: {
    opacity: 0.46,
  },
  header: {
    alignItems: 'center',
    marginBottom: 26,
  },
  headerCompact: {
    marginBottom: 20,
  },
  logo: {
    width: 56,
    height: 56,
    marginBottom: 14,
    resizeMode: 'contain',
  },
  verificationIcon: {
    width: 60,
    height: 60,
    marginBottom: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(92,164,255,0.30)',
    borderRadius: 17,
    backgroundColor: 'rgba(10,132,255,0.14)',
  },
  title: {
    maxWidth: '100%',
    color: '#FFFFFF',
    fontSize: 25,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 30,
    textAlign: 'center',
  },
  subtitle: {
    maxWidth: 292,
    marginTop: 6,
    color: 'rgba(235,238,245,0.62)',
    fontSize: 14,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 20,
    textAlign: 'center',
  },
  form: {
    gap: 12,
  },
  nameRow: {
    flexDirection: 'row',
    gap: 12,
  },
  nameField: {
    minWidth: 0,
    flex: 1,
  },
  inputShell: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.14)',
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  inputShellFocused: {
    borderColor: '#0A84FF',
  },
  inputShellDisabled: {
    opacity: 0.56,
  },
  input: {
    minWidth: 0,
    flex: 1,
    paddingVertical: 0,
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '400',
    letterSpacing: 0,
  },
  codeInput: {
    fontSize: 22,
    fontWeight: '700',
    letterSpacing: 6,
    textAlign: 'center',
  },
  passwordToggle: {
    width: 40,
    height: 40,
    marginRight: -8,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
  },
  passwordTogglePressed: {
    backgroundColor: 'rgba(92,176,255,0.12)',
  },
  requirements: {
    gap: 8,
    marginTop: 2,
    paddingHorizontal: 2,
  },
  requirement: {
    minHeight: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  requirementIcon: {
    width: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
    backgroundColor: 'rgba(255,255,255,0.10)',
  },
  requirementIconMet: {
    backgroundColor: '#30B85A',
  },
  requirementText: {
    flexShrink: 1,
    color: 'rgba(235,238,245,0.50)',
    fontSize: 12.5,
    fontWeight: '500',
    letterSpacing: 0,
    lineHeight: 18,
  },
  requirementTextMet: {
    color: 'rgba(235,238,245,0.90)',
  },
  status: {
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: 'rgba(229,72,77,0.34)',
    borderRadius: 14,
    backgroundColor: 'rgba(229,72,77,0.12)',
  },
  statusText: {
    color: '#FFB4B8',
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 19,
  },
  primaryButton: {
    minHeight: 54,
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingHorizontal: 20,
    borderRadius: 15,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000000',
    shadowOpacity: 0.34,
    shadowRadius: 11,
    shadowOffset: { width: 0, height: 8 },
  },
  primaryButtonPressed: {
    backgroundColor: '#E9E9ED',
    transform: [{ scale: 0.985 }],
  },
  primaryButtonDisabled: {
    opacity: 0.56,
  },
  primaryButtonText: {
    flexShrink: 1,
    color: '#12141A',
    fontSize: 16.5,
    fontWeight: '700',
    letterSpacing: 0,
    textAlign: 'center',
  },
  footer: {
    minHeight: 44,
    marginTop: 10,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  footerText: {
    color: 'rgba(235,238,245,0.60)',
    fontSize: 14,
    fontWeight: '400',
    letterSpacing: 0,
  },
  footerButton: {
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: 4,
    borderRadius: 8,
  },
  footerButtonPressed: {
    backgroundColor: 'rgba(92,176,255,0.12)',
  },
  footerButtonText: {
    color: '#5CB0FF',
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0,
  },
});
