import { StyleSheet } from 'react-native';

import { authColors, authRadius } from './authDesign';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: authColors.background,
  },
  keyboardShell: {
    flex: 1,
  },
  handoffBackButton: {
    position: 'absolute',
    left: 16,
    top: 14,
    zIndex: 3,
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 0.5,
    borderColor: 'rgba(255,255,255,0.16)',
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.10)',
  },
  handoffBackButtonPressed: {
    backgroundColor: 'rgba(255,255,255,0.17)',
    transform: [{ scale: 0.96 }],
  },
  handoffScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 30,
    paddingBottom: 42,
    paddingTop: 92,
  },
  handoffScrollContentCompact: {
    justifyContent: 'flex-start',
    paddingHorizontal: 22,
    paddingBottom: 28,
    paddingTop: 86,
  },
  handoffHeader: {
    alignItems: 'center',
    marginBottom: 44,
  },
  handoffLogo: {
    width: 76,
    height: 76,
    marginBottom: 14,
    resizeMode: 'contain',
  },
  handoffBrand: {
    maxWidth: '100%',
    color: '#FFFFFF',
    fontSize: 32,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 38,
    textAlign: 'center',
  },
  handoffForm: {
    gap: 14,
  },
  handoffInputShell: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.14)',
    borderRadius: 15,
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  handoffInputShellFocused: {
    borderColor: '#0A84FF',
  },
  handoffInput: {
    minWidth: 0,
    flex: 1,
    paddingVertical: 0,
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '400',
    letterSpacing: 0,
  },
  handoffPrimaryButton: {
    minHeight: 54,
    marginTop: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingHorizontal: 20,
    borderRadius: 15,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000000',
    shadowOpacity: 0.34,
    shadowRadius: 11,
    shadowOffset: { width: 0, height: 8 },
  },
  handoffPrimaryButtonPressed: {
    backgroundColor: '#E9E9ED',
    transform: [{ scale: 0.985 }],
  },
  handoffPrimaryButtonDisabled: {
    opacity: 0.56,
  },
  handoffPrimaryButtonText: {
    flexShrink: 1,
    color: '#12141A',
    fontSize: 16.5,
    fontWeight: '700',
    letterSpacing: 0,
    textAlign: 'center',
  },
  handoffFooter: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  handoffFooterButton: {
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: 4,
    borderRadius: 8,
  },
  handoffFooterButtonPressed: {
    backgroundColor: 'rgba(92,176,255,0.12)',
  },
  handoffFooterMutedText: {
    color: '#8E8E93',
    fontSize: 14,
    fontWeight: '500',
    letterSpacing: 0,
  },
  handoffFooterLinkText: {
    color: '#5CB0FF',
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0,
  },
  handoffFooterDot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: 'rgba(255,255,255,0.25)',
  },
  flowScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 30,
    paddingBottom: 40,
    paddingTop: 92,
  },
  flowScrollContentCompact: {
    justifyContent: 'flex-start',
    paddingHorizontal: 22,
    paddingBottom: 28,
    paddingTop: 86,
  },
  flowContent: {
    alignSelf: 'center',
    width: '100%',
    maxWidth: 390,
  },
  flowHeader: {
    alignItems: 'center',
    marginBottom: 32,
  },
  flowHeaderCompact: {
    marginBottom: 24,
  },
  flowLogo: {
    width: 64,
    height: 64,
    marginBottom: 16,
    resizeMode: 'contain',
  },
  flowIconTile: {
    width: 60,
    height: 60,
    marginBottom: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(92,176,255,0.20)',
    borderRadius: 17,
    backgroundColor: 'rgba(92,176,255,0.10)',
  },
  flowTitle: {
    maxWidth: '100%',
    color: '#FFFFFF',
    fontSize: 25,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 30,
    textAlign: 'center',
  },
  flowSubtitle: {
    maxWidth: 320,
    marginTop: 9,
    color: '#A6A8AE',
    fontSize: 14,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 20,
    textAlign: 'center',
  },
  flowLinkRow: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  flowSecondaryLink: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    borderRadius: 8,
  },
  flowHelperText: {
    marginTop: 8,
    color: '#8E8E93',
    fontSize: 13,
    fontWeight: '500',
    letterSpacing: 0,
    lineHeight: 18,
  },
  codeCellRow: {
    position: 'relative',
    width: '100%',
    minHeight: 58,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  codeCell: {
    height: 58,
    minWidth: 0,
    maxWidth: 46,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.14)',
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  codeCellFilled: {
    borderColor: 'rgba(92,176,255,0.45)',
    backgroundColor: 'rgba(92,176,255,0.09)',
  },
  codeCellFocused: {
    borderColor: '#0A84FF',
  },
  codeCellText: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 27,
    textAlign: 'center',
  },
  codeInputOverlay: {
    ...StyleSheet.absoluteFillObject,
    color: 'transparent',
    backgroundColor: 'transparent',
    fontSize: 1,
    opacity: 0.02,
  },
  inputShellDisabled: {
    opacity: 0.46,
  },
  passwordToggle: {
    width: 40,
    height: 40,
    marginRight: -8,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: authRadius.pill,
  },
  passwordTogglePressed: {
    backgroundColor: authColors.accentTint,
  },
  passwordToggleDisabled: {
    opacity: 0.46,
  },
  statusBox: {
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderRadius: authRadius.row,
    backgroundColor: authColors.glassQuiet,
  },
  noticeBox: {
    borderColor: authColors.warningBorder,
    backgroundColor: authColors.warningSoft,
  },
  errorBox: {
    borderColor: authColors.criticalBorder,
    backgroundColor: authColors.criticalSoft,
  },
  successBox: {
    borderColor: authColors.successBorder,
    backgroundColor: authColors.successSoft,
  },
  statusText: {
    color: authColors.muted,
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 19,
  },
  noticeText: {
    color: authColors.warning,
  },
  errorText: {
    color: authColors.criticalText,
  },
  successText: {
    color: authColors.success,
  },
  challengeHintBox: {
    minHeight: 40,
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: authColors.glassBorder,
    borderRadius: authRadius.row,
    backgroundColor: authColors.glassQuiet,
  },
  challengeHintBoxDanger: {
    borderColor: authColors.criticalBorder,
    backgroundColor: authColors.criticalSoft,
  },
  challengeHintText: {
    color: authColors.muted,
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 19,
  },
  challengeHintTextDanger: {
    color: authColors.criticalText,
  },
  savedSessionRetryButton: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: authColors.accentBorder,
    borderRadius: authRadius.pill,
    backgroundColor: authColors.accentTint,
  },
  savedSessionRetryButtonPressed: {
    backgroundColor: authColors.glassQuiet,
    transform: [{ scale: 0.985 }],
  },
  savedSessionRetryButtonText: {
    flexShrink: 1,
    maxWidth: 230,
    color: authColors.accent,
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0,
    textAlign: 'center',
  },
});
