import { StyleSheet } from 'react-native';

import { authColors, authRadius } from './authDesign';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: authColors.background,
  },
  keyboardShell: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 28,
  },
  scrollContentCompact: {
    justifyContent: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 20,
  },
  cardFrame: {
    alignSelf: 'center',
    width: '100%',
    maxWidth: 448,
    borderRadius: authRadius.card,
    shadowColor: '#060812',
    shadowOpacity: 0.45,
    shadowRadius: 30,
    shadowOffset: { width: 0, height: 18 },
    elevation: 12,
  },
  card: {
    width: '100%',
    paddingHorizontal: 28,
    paddingBottom: 24,
    paddingTop: 28,
    borderWidth: 1,
    borderColor: authColors.glassBorder,
    borderTopColor: authColors.glassTopEdge,
    borderRadius: authRadius.card,
    backgroundColor: authColors.glass,
    overflow: 'hidden',
  },
  cardBlur: {
    ...StyleSheet.absoluteFillObject,
  },
  cardCompact: {
    paddingHorizontal: 20,
    paddingBottom: 20,
    paddingTop: 24,
  },
  backButton: {
    position: 'absolute',
    left: 16,
    top: 16,
    zIndex: 2,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: authRadius.pill,
    backgroundColor: 'transparent',
  },
  backButtonPressed: {
    backgroundColor: authColors.glassQuiet,
  },
  backButtonDisabled: {
    opacity: 0.46,
  },
  header: {
    gap: 7,
    marginBottom: 20,
    paddingTop: 34,
  },
  headerCompact: {
    marginBottom: 16,
    paddingTop: 30,
  },
  eyebrow: {
    color: authColors.accent,
    fontFamily: 'Menlo',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 16,
    textTransform: 'uppercase',
  },
  title: {
    maxWidth: '100%',
    color: authColors.text,
    fontSize: 32,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 37,
    textTransform: 'uppercase',
  },
  titleCompact: {
    fontSize: 27,
    lineHeight: 32,
  },
  subtitle: {
    maxWidth: '100%',
    color: authColors.muted,
    fontSize: 15,
    fontWeight: '500',
    letterSpacing: 0,
    lineHeight: 22,
  },
  form: {
    gap: 16,
  },
  field: {
    gap: 8,
  },
  labelRow: {
    minHeight: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  label: {
    flexShrink: 1,
    color: authColors.muted,
    fontFamily: 'Menlo',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 16,
    textTransform: 'uppercase',
  },
  inlineButton: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
    borderRadius: authRadius.row,
  },
  inlineButtonPressed: {
    backgroundColor: authColors.accentTint,
  },
  inlineButtonDisabled: {
    opacity: 0.46,
  },
  inlineButtonText: {
    color: authColors.accent,
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0,
  },
  inputShell: {
    minHeight: 50,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: authColors.inputBorder,
    borderRadius: authRadius.row,
    backgroundColor: authColors.input,
  },
  inputShellFocused: {
    borderColor: authColors.accentFocus,
    shadowColor: authColors.accent,
    shadowOpacity: 0.7,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 0 },
  },
  inputShellDisabled: {
    opacity: 0.46,
  },
  input: {
    minWidth: 0,
    flex: 1,
    color: authColors.text,
    fontSize: 16,
    fontWeight: '500',
    letterSpacing: 0,
    paddingVertical: 0,
  },
  codeInput: {
    fontFamily: 'Menlo',
    fontSize: 20,
    fontWeight: '700',
    letterSpacing: 0,
  },
  passwordToggle: {
    width: 40,
    height: 40,
    marginRight: -8,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: authRadius.pill,
  },
  passwordTogglePressed: {
    backgroundColor: authColors.accentTint,
  },
  passwordToggleDisabled: {
    opacity: 0.46,
  },
  helperText: {
    color: authColors.muted,
    fontSize: 13,
    fontWeight: '500',
    letterSpacing: 0,
    lineHeight: 19,
  },
  statusBox: {
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderRadius: authRadius.row,
    backgroundColor: authColors.glassQuiet,
  },
  noticeBox: {
    borderColor: authColors.warningBorder,
    backgroundColor: authColors.warningSoft,
  },
  errorBox: {
    borderColor: authColors.criticalBorder,
    backgroundColor: authColors.criticalSoft,
  },
  successBox: {
    borderColor: authColors.successBorder,
    backgroundColor: authColors.successSoft,
  },
  statusText: {
    color: authColors.muted,
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 19,
  },
  noticeText: {
    color: authColors.warning,
  },
  errorText: {
    color: authColors.criticalText,
  },
  successText: {
    color: authColors.success,
  },
  challengeHintBox: {
    minHeight: 40,
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: authColors.glassBorder,
    borderRadius: authRadius.row,
    backgroundColor: authColors.glassQuiet,
  },
  challengeHintBoxDanger: {
    borderColor: authColors.criticalBorder,
    backgroundColor: authColors.criticalSoft,
  },
  challengeHintText: {
    color: authColors.muted,
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 19,
  },
  challengeHintTextDanger: {
    color: authColors.criticalText,
  },
  primaryButton: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingHorizontal: 22,
    borderRadius: authRadius.pill,
    backgroundColor: authColors.accent,
    shadowColor: authColors.accent,
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 7 },
  },
  primaryButtonPressed: {
    backgroundColor: authColors.accentPressed,
    transform: [{ scale: 0.985 }],
  },
  primaryButtonDisabled: {
    opacity: 0.46,
    shadowOpacity: 0,
  },
  primaryButtonText: {
    flexShrink: 1,
    maxWidth: 260,
    color: authColors.accentInk,
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0,
    textAlign: 'center',
  },
  secondaryButton: {
    minHeight: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingHorizontal: 22,
    borderWidth: 1,
    borderColor: authColors.glassBorder,
    borderTopColor: authColors.glassTopEdge,
    borderRadius: authRadius.pill,
    backgroundColor: authColors.glassQuiet,
  },
  secondaryButtonPressed: {
    backgroundColor: authColors.accentTint,
    transform: [{ scale: 0.985 }],
  },
  secondaryButtonDisabled: {
    opacity: 0.46,
  },
  secondaryButtonText: {
    flexShrink: 1,
    maxWidth: 260,
    color: authColors.text,
    fontSize: 15,
    fontWeight: '600',
    letterSpacing: 0,
    textAlign: 'center',
  },
  savedSessionRetryButton: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: authColors.accentBorder,
    borderRadius: authRadius.pill,
    backgroundColor: authColors.accentTint,
  },
  savedSessionRetryButtonPressed: {
    backgroundColor: authColors.glassQuiet,
    transform: [{ scale: 0.985 }],
  },
  savedSessionRetryButtonText: {
    flexShrink: 1,
    maxWidth: 230,
    color: authColors.accent,
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0,
    textAlign: 'center',
  },
});
